name: New Environment
values:
  - key: baseUrl
    value: 'http://localhost:8000'
    enabled: true
  - key: readToken
    value: 'reader-token'
    enabled: true
  - key: publishToken
    value: 'publisher-token'
    enabled: true
  - key: adminToken
    value: 'admin-token'
    enabled: true
